apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-api-deployment
  labels:
    app: common-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-api
  template:
    metadata:
      labels:
        app: common-api
    spec:
      containers:
      - name: common-api
        image: $REGISTRY_HARBOR_URL/$PROJECT_NAME/$IMAGE_NAME:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 3334
        env:     
        - name: HAPROXY_IP
          value: "${HAPROXY_URL}"  
        - name: CONTAINER_PLATFORM_API_URL
          value: "api-deployment.default.svc.cluster.local:3333"
        - name: MARIADB_USER_ID
          value: cp-admin
        - name: MARIADB_USER_PASSWORD
          value: PaaS-TA@2021
      imagePullSecrets:
        - name: cp-secret
      nodeSelector:
        kubernetes.io/hostname: paasta-cp-cluster-2

---
apiVersion: v1
kind: Service
metadata:
  name: common-api-deployment
  labels:
    app: common-api
  namespace: default
spec:
  ports:
  - nodePort: 30434
    port: 3334
    protocol: TCP
    targetPort: 3334
  selector:
    app: common-api
  type: NodePort
